### ISSUE TITLE
Outline Emoji

### ISSUE THREAD

**Issue by petatemarvin26** [tom-james-watson/Emote#83] opened 2022-11-04 11:45 UTC
I expect all of these emoji are colored, but some of the emoji is just an outline, is there other configuration should to setup or is this a bug?

![image](https://user-images.githubusercontent.com/46154422/199964973-084ec0c2-f10a-4e65-ae62-c6be5c959f61.png)

**Comment by waldyrious** [comment] 2022-11-04 15:53
Seems to be a duplicate of  #71.

**Closed** 2023-06-20 11:21 UTC
