### ISSUE TITLE
stay open when selecting an emoji

### ISSUE THREAD

**Issue by Heus-Sueh** [tom-james-watson/Emote#127] opened 2023-07-31 00:43 UTC
remain open even when selecting an emoji, it's very frustrating when you need to select several emoji and the program closes every time you select one

**Comment by tom-james-watson** [comment] 2023-07-31 07:06
Duplicate of https://github.com/tom-james-watson/Emote/issues/37

See note about how to select multiple emojis at once.

**Closed by tom-james-watson** 2023-07-31 07:06 UTC
