### ISSUE TITLE
The layout is not shown properly after 4.0

### ISSUE THREAD

**Issue by soygabimoreno** [tom-james-watson/Emote#122] opened 2023-07-06 06:48 UTC
Hi and thank you so much for such an excellent fruitful app! :muscle: 

I think this started from [version 4.0](https://github.com/tom-james-watson/Emote/releases/tag/v4.0.0) because it happened to me 2 days ago (probably I didn't upgrade Emote until that moment)

The layout is broken:

![image](https://github.com/tom-james-watson/Emote/assets/1880789/c2dc3832-658d-47c2-923d-c9a826140e08)

I am using Ubuntu 23.04 with KDE.

![image](https://github.com/tom-james-watson/Emote/assets/1880789/802528a0-ce43-4a8a-b91e-0e56e2c01755)

If I can help you by providing more info, please, let me know.

BTW, how could I try a previous version?

**Comment by floviolleau** [comment] 2023-07-06 13:08
Hi,

Same issue here on stock Ubuntu

**Comment by tom-james-watson** [comment] 2023-07-06 14:26
Closing as duplicate of https://github.com/tom-james-watson/Emote/issues/115

**Closed by tom-james-watson** 2023-07-06 14:26 UTC

**Comment by soygabimoreno** [comment] 2023-07-06 17:17
Sorry for the noise. I didn't see the other issue!
