### ISSUE TITLE
UI issue on Ubuntu 23.04

### ISSUE THREAD

**Issue by tadasgo** [tom-james-watson/Emote#134] opened 2023-10-20 05:37 UTC
Hello,

noticed that on ubuntu 23.04 the emojis are extra large that results in out-scaled UI. Is there are an easy way to solve this?
Application installed using snap store, version 4.0.1

Expected:
![image](https://github.com/tom-james-watson/Emote/assets/61449927/71fedbbf-7068-4e6a-a47f-2e7b81737975)

Ubuntu 23.04:
![Screenshot from 2023-10-20 08-31-21](https://github.com/tom-james-watson/Emote/assets/61449927/f5f44e68-7150-4cb4-936f-e254269a8f6a)

**Comment by tom-james-watson** [comment] 2023-10-20 08:50
This is a duplicate of https://github.com/tom-james-watson/Emote/issues/115. Using the flatpak version should avoid this issue.

**Closed by tom-james-watson** 2023-10-20 08:50 UTC

**Comment by tom-james-watson** [comment] 2023-10-22 17:07
This should now be fixed in snap version 4.1.0, thanks to https://github.com/tom-james-watson/Emote/pull/135
