### ISSUE TITLE
☹ is the only emoji that doesnt fit

### ISSUE THREAD

**Issue by ThatOneCalculator** [tom-james-watson/Emote#23] opened 2020-12-28 07:12 UTC
![image](https://user-images.githubusercontent.com/44733677/103196371-f35b2e00-4898-11eb-9db0-9f104f70382e.png)

Need I say more?

**Comment by tom-james-watson** [comment] 2021-01-01 12:53
What distro is this? Are you installing from snap?

**Comment by ThatOneCalculator** [comment] 2021-01-01 17:17
Arch installing from the AUR

**Comment by tom-james-watson** [comment] 2021-01-01 19:20
I don't maintain the AUR package. Pinging @lkrms, who is the person that packages it for arch.

With the snap the fonts are bundled in, so this doesn't happen.

**Comment by lkrms** [comment] 2021-01-03 22:48
Interesting. The only fonts packaged in the snap that I can see are DejaVu variants, none of which contain coloured emoji glyphs. Also, the ☹ emoji doesn't render correctly in official screenshots either, e.g. on the snap store:

![image](https://user-images.githubusercontent.com/2563783/103490459-fa250a80-4e6f-11eb-8f1b-5b092e3e25d0.png)

It would be odd for Noto Color Emoji to exclude this particular glyph. Might be worth a closer look, @tom-james-watson?

**Comment by ThatOneCalculator** [comment] 2021-01-07 07:07
Ok, so I did some research. This isn't your fault, or the AUR version's fault. It's GOOGLE'S fault. There have been many documented instances of ☹ not showing correctly, both on mobile and desktop. I was able to reproduce it with my phone, by typing that emoji into a plain HTML input box. So yeah, Google's buggy.

**Comment by lkrms** [comment] 2021-01-08 11:25
I've been looking into this too, especially after noticing the same behaviour in other apps. After too much time wrangling `fontconfig`, some findings:

1. Noto Color Emoji contains the relevant glyph, so it's not Google's fault (happy as I would be for this to be true)

2. ☹ isn't the only emoji rendering this way, e.g. compare ☮ ✝ ☪ etc. in these screenshots:
    
    <img width="40%" alt="Screen Shot 2021-01-08 at 9 53 37 pm" src="https://user-images.githubusercontent.com/2563783/104007630-5e432800-51fc-11eb-8bca-985f72ca8dbf.png"> <img width="40%"  alt="Screen Shot 2021-01-08 at 9 54 24 pm" src="https://user-images.githubusercontent.com/2563783/104007643-61d6af00-51fc-11eb-82ba-9b2cc215f05e.png">

3. The issue is caused by a combination of `fontconfig`'s handling of emoji fonts and `sans-serif` / `serif` / `monospace` aliases; `fontconfig` defaulting to generic fonts that include handful of glyphs at emoji codepoints (DejaVu Sans is responsible for this aberration at U+2639, for example); and some characters in [emojis.json](https://github.com/tom-james-watson/Emote/blob/master/static/emojis.json) being, in Unicode parlance, "unqualified" (see [here](https://unicode.org/Public/emoji/13.1/emoji-test.txt)).

I've got it working with a [custom `fontconfig` rule](https://github.com/lkrms/lk-settings/blob/master/fonts/emoji-fix.conf) that strips emoji glyphs from every font family except Noto Color Emoji, but I'll try to come up with a cleaner patch and open a PR.

**Comment by tom-james-watson** [comment] 2021-01-15 21:13
Fixed by @lkrms in https://github.com/tom-james-watson/Emote/pull/24 (thanks!). Just released version 1.3.0 of the snap which includes this fix.

**Closed by tom-james-watson** 2021-01-15 21:13 UTC
