### ISSUE TITLE
When active window is a Terminal use Ctrl-Shift-V to paste, not Ctrl-V

### ISSUE THREAD

**Issue by rbreaves** [tom-james-watson/Emote#66] opened 2022-04-13 13:57 UTC
I know this will be most helpful for x11 initially but here is a list of wm_class names you can use for the terminal app grouping.

Be sure to make things case insensitive.

"alacritty","cutefish-terminal","deepin-terminal","eterm","gnome-terminal","guake","hyper","io.elementary.terminal","kitty","konsole","lxterminal","mate-terminal","qterminal","st","sakura","station","tabby","terminator","termite","tilda","tilix","urxvt","xfce4-terminal","xterm"

**Comment by reitzig** [comment] 2022-05-07 10:53
Same as #44 ?

**Comment by tom-james-watson** [comment] 2022-05-07 11:06
Closing as duplicate of https://github.com/tom-james-watson/Emote/issues/44

**Closed by tom-james-watson** 2022-05-07 11:06 UTC
