### ISSUE TITLE
Do not use (main) clipboard

### ISSUE THREAD

**Issue by reitzig** [tom-james-watson/Emote#41] opened 2021-05-28 10:21 UTC
emote uses the "main" clipboard to paste emojis; that tends to break some workflows ("copy image; write tweet; paste im ... fuck").

As per [askubuntu#591686](https://askubuntu.com/q/591686/69674), `xdotool` can send Unicode characters directly which should provide a neat solution that does not "pollute" the clipboard.

As an alternative, you could use `xsel -s` to use the seconday selection instead, in the hope of causing fewer conflicts.

**Comment by rbreaves** [comment] 2022-04-13 13:59
Does this fix work with terminals? #66

**Comment by tom-james-watson** [comment] 2022-05-06 12:05
Pull requests are welcome

**Comment by paullaffitte** [comment] 2022-05-06 12:38
As I realize that I cannot reasonably stop using this software (I have to admit that it is quite useful) I will try to present a pull request soon

**Comment by reitzig** [comment] 2022-05-07 10:52
@tom-james-watson Was #42 a reasonable place to start?

**Comment by tom-james-watson** [comment] 2022-05-07 11:06
Sorry I forgot that that PR existed. My opinion on that is still https://github.com/tom-james-watson/Emote/pull/42#issuecomment-860185632. Restoring clipboard contents is problematic because of the issues mentioned. The main thing to bear in mind as well is that on Wayland, which is going to be the default for probably the majority of users over the next year or two, cannot perform a paste and so relies entirely on copying.

**Comment by paullaffitte** [comment] 2022-05-07 14:51
Sorry I didn't see your answers before doing the PR. #42 looks to be exactly what I was thinking about. I just didn't know that I needed to focus the window in order to type in it. But the main issue seems to be with Wayland from what I understand ? Why not merging #42 now and then wait until mutter supports virtual-keyboard-unstable-v1 to use wtype in Wayland ?

**Comment by reitzig** [comment] 2022-05-10 11:51
> Restoring clipboard contents is problematic because of the issues mentioned.

I for one would be fine with a configuration flag switching between using clipboard and fake-typing. Using the clipboard still frequently breaks my (work)flow, esp. in combination with taking screenshots.

>  The main thing to bear in mind as well is that on Wayland, which is going to be the default for probably the majority of users over the next year or two, cannot perform a paste and so relies entirely on copying.

I can't comment on Wayland; your prognosis seems rather optimistic to me, though. To my knowledge, Ubuntu 22.04 LTS _does_ use Wayland by default but I find many voices saying it doesn't work well for them, still. I for one see little advantage in using Wayland with i3 (which would mean replacing i3 completely, no less); not enough to rewrite a whole bunch of scripts and configs, anyway. Not that X is _good_, but I've learned to live with it, as have roughly all Linux desktop users. :tipping_hand_man: Anyway, that's all just guesswork at this point. Suffice to say, I don't think using a prognosis regarding adoption of Wayland is a good argument for either side of this.

**Comment by reitzig** [comment] 2022-08-19 10:29
FWIW, it seems [espanso](https://github.com/espanso/espanso) has solved the very same issue. They reference

>    Thanks to [libxdo](https://github.com/jordansissel/xdotool) and [xclip](https://github.com/astrand/xclip), used to implement the Linux port.
>    Thanks to [libxkbcommon](https://xkbcommon.org/) and [wl-clipboard](https://github.com/bugaevc/wl-clipboard), used to implement the Wayland port.
>    Thanks to [wxWidgets](https://www.wxwidgets.org/) for providing a powerful cross-platform GUI library.

**Comment by tom-james-watson** [comment] 2022-08-19 11:53
By the same issue do you mean injecting text under wayland? I have spent about an hour looking through these / doing some research.

As far as I can tell, wl-clipboard is only useful for cli interaction.

It looks like maybe with libxkbcommon it may be possible, but there's a lot of unknowns (to me) and concepts and systems that I'm not familiar with here, as well as a language I'm not very familiar with (C).

I personally am stuck. If somebody knows of an approach to either simualte a keypress (to do ctrl+v) or of some way of globally injecting text with wayland, please let me know!

**Comment by tom-james-watson** [comment] 2023-06-20 13:59
I am going to close this out, because for now copying the selection to clipboard is the intended behaviour of the app. I can understand the argument for X11 to not do this, but the default on linux these days is Wayland and currently there is no known way to recreate the insertion of arbitrary characters with Wayland. I don't want the app to behave different on X11 vs Wayland, so I don't think it makes sense to make any changes here.

I would potentially accept a PR that implements an option in preferences that turns off clipboard copying, as long as by default copying is turned on and if the preference is only visible if running under X11. I'll close this out because at the moment this is not planned. Thanks!

**Closed as completed by tom-james-watson** 2023-06-20 13:59 UTC
