### ISSUE TITLE
Pasting into apps that don't support Ctrl-V

### ISSUE THREAD

**Issue by CatalinFrancu** [tom-james-watson/Emote#81] opened 2022-09-30 06:36 UTC
First and foremost thanks for Emote! It's great to have one universal tool instead of multiple per-app plugins.

Now, I have the XFCE4 window manager and I use Emacs to compose emails. When I hit `Ctrl-Alt-E` and select an icon (either by left-clicking or by typing a substring followed by `Enter`), instead of the emoji appearing, Emacs scrolls down one page. I suspect this has to do with `Ctrl-V` being the default Emacs key for page down. I tested that assumption in xfce4-terminal, which also has a different shortcut for pasting (`Ctrl-Shift-V`). No emoji shows up, but a Ctrl-V code is sent. In programs that do use `Ctrl-V` for pasting (Signal, Discord, browsers) the emoji does show up.

As a workaround for Emacs, I can right-click the icon in Emote to have it copied, but not pasted, then hit `Esc` to dismiss emote and paste the emoji manually. But that feels unwieldy.

It would be nice to see a proper fix!

**Comment by pedramardakani** [comment] 2022-12-23 08:53
I do agree @CatalinFrancu 👍 

Currently I just navigate to another page and select my emoji, but since there is no keyboard focus, the emoji won't be pasted anywhere. Still, it sits in the clipboard. Then I navigate back to Emacs or Shell or whatever I am using, and handle the pasting myself. Doing all of this is still quicker than clicking by mouse 😅

The quick and dirty workaround may be to add another keyboard shortcut that just copies to clipboard, then let the user handle the pasting.

**Comment by tom-james-watson** [comment] 2023-06-20 13:55
Duplicate of https://github.com/tom-james-watson/Emote/issues/81

**Closed by tom-james-watson** 2023-06-20 13:55 UTC

**Comment by waldyrious** [comment] 2023-06-21 09:43
I think you meant duplicate of #41, right? #81 is this issue. (Funny that GitHub allows marking an issue as a duplicate of itself!)

**Comment by tom-james-watson** [comment] 2023-06-21 10:48
Oops, I meant https://github.com/tom-james-watson/Emote/issues/44
