### ISSUE TITLE
Emote startup is really slow

### ISSUE THREAD

**Issue by dcts** [tom-james-watson/Emote#74] opened 2022-06-20 17:03 UTC
Is there a way to imrpove speed of the `emote` command or somehow run the program in the background? My issue is that every time I open the program it takes ~2 seconds to load. 

This is way too long and a real slow down in the flow. Just wondering if this is normal or if its me not properly setting up the program. 

Thanks for any help. Love the look and feel of the picker!

**Comment by tom-james-watson** [comment] 2022-06-20 21:32
Closing as duplicate of https://github.com/tom-james-watson/Emote/issues/54

**Comment by waldyrious** [comment] 2022-07-04 10:12
@tom-james-watson you seem to have forgotten to actually close the issue! :smile:

**Closed** 2022-07-04 10:41 UTC
